#!/bin/bash

# https://docs.openstack.org/diskimage-builder/latest/developer/developing_elements.html

if [ "${DIB_DEBUG_TRACE:-0}" -gt 0 ]; then
	set -x
fi

set -eu
set -o pipefail

cp -rv /tmp/in_target.d/element-overlay/* /

mkdir -p /opt/custom-deploy
for script in /tmp/in_target.d/custom-deploy-scripts/*.sh; do
	script_name=$(basename "$script")
	install -D -m 0755 "$script" "/opt/custom-deploy/$script_name"
done
