#!/bin/bash

# https://docs.openstack.org/diskimage-builder/latest/developer/developing_elements.html

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
	set -x
fi

set -eu
set -o pipefail

cp -rv /tmp/in_target.d/element-overlay/* /

mkdir -p /etc/systemd/system/multi-user.target.wants
mkdir -p /etc/systemd/system/ironic-python-agent.service.requires

ln -sf ../dhclient.service /etc/systemd/system/multi-user.target.wants/dhclient.service
ln -sf ../dhclient.service /etc/systemd/system/ironic-python-agent.service.requires/dhclient.service
