#!/bin/bash

# https://docs.openstack.org/diskimage-builder/latest/developer/developing_elements.html

if [ "${DIB_DEBUG_TRACE:-0}" -gt 0 ]; then
	set -x
fi

set -eu
set -o pipefail

mkdir -p "$TMP_HOOKS_PATH/element-overlay"
cp -rv "$(dirname "$0")/../overlay/"* "$TMP_HOOKS_PATH/element-overlay/"

mkdir -p "$TMP_HOOKS_PATH/custom-deploy-scripts"
cp -v "$(dirname "$0")/../scripts/"*.sh "$TMP_HOOKS_PATH/custom-deploy-scripts/"
